account.withdraw(150)
account = BankAccount()
t1 = threading.Thread(target=deposit_task, args=(account,))
t2 = threading.Thread(target=withdraw_task, args=(account,))t3 = threading.Thread(target=deposit_task, args=(account,))
t1.start()
t2.start()
t3.start()
t1.join()
t2.join()
t3.join()
print(f"\nFinalAccount Balance: {account.balance}")